### ISSUE TITLE
회원가입 폼 구현(이메일, 비밀번호, 비밀번호 확인, 닉네임, 언어,  관심사 설정 등)

### ISSUE THREAD

**Issue by JayLee-98** [LingoBell/LingoBell-FrontEnd#1]

**Comment by modaing** [comment]
현재 로그인 기능은 firebase 이용하여 구글 계정으로 로그인 기능만 가능한 상황이라 해당 이슈 닫겠습니다. 추후 이메일 회원가입과 로그인 기능 추가할 시 다시 재오픈하겠습니다.
