### ISSUE TITLE
이메일 인증 폼 구현(회원정보 찾기)

### ISSUE THREAD

**Issue by JayLee-98** [LingoBell/LingoBell-FrontEnd#3]

**Comment by modaing** [comment]
현재 로그인 기능은 firebase 이용하여 구글 계정으로 로그인 기능만 가능한 상황이라 해당 이슈 닫겠습니다. 
추후 이메일 회원가입과 로그인 기능 추가하여 이메일 인증 폼이 필요한 경우 다시 재오픈하겠습니다.
